apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-storage
  namespace: m2k8s
  labels:
    app: profile
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: root
  namespace: m2k8s
type: Opaque
data:
  username: LW4gYWRtaW4K
  password: LW4gc2VjcmV0Cg==
---
apiVersion: v1
kind: Secret
metadata:
  name: empuser
  namespace: m2k8s
type: Opaque
data:
  username: LW4gZW1wdXNlcgo=
  password: LW4gcGFzc3dvcmQK
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: m2k8s
  labels:
    app: profile
spec:
  ports:
    - port: 3306
  selector:
    app: profile
    tier: mysql
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: db
  namespace: m2k8s
  labels:
    app: profile
spec:
  selector:
    matchLabels:
      app: profile
      tier: mysql
  template:
    metadata:
      labels:
        app: profile
        tier: mysql
    spec:
      containers:
      - image: mysql:8
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: secret
        - name: MYSQL_USER
          value: empuser
        - name: MYSQL_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: profiles
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-storage

