version: '3.7'

volumes:
  mysql-data:
  profile-data:
  
services:

  profile:
    image: aktur/m2k8s:latest
    build: .
    ports:
      - 8080:8080
    volumes:
      - profile-data:/data

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 81:8080